package com.windhoverlabs.com.video;

public enum EReturnCode {
  OK_CONGESTED,
  OK_NO_OUTPUT,
  OK_FRAME_SKIPPED,
  OK_QUEUE_EMPTY,
  OK_EOF,
  OK,
  FAILED_INITIALIZATION,
  INVALID_CONFIG,
  INVALID_PARAM,
  INVALID_INPUT_REF,
  FAILED_EXECUTE,
  UNUSED_PARAM
};
